# -*- coding: utf-8 -*-
"""train_delay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvrgqMdRZ-3nw6T9cTRzFtnizuGUHpNk
"""

import requests
from bs4 import BeautifulSoup
from linebot import LineBotApi
from linebot.models import TextSendMessage

# Function to get the first dt tag text from a website
def get_first_dt_text(url):
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        dt_tag = soup.find('dt')
        if dt_tag:
            return dt_tag.get_text()
    return None

# Function to send a message via LINE
def send_line_message(token, user_id, message):
    line_bot_api = LineBotApi(token)
    line_bot_api.push_message(user_id, TextSendMessage(text=message))

# Example usage
url = 'https://transit.yahoo.co.jp/diainfo/40/0'  # Replace with the actual URL
line_access_token = 'Wrbc66+sRrp3Hnn+j1x/j17xHxoq4PW+69ny9v+9zYXyWxauLeGRRL2S97IqX5qrI8Dz6k0Cv3J/38FA6XATVJTYDGGNP85xv0/VC2D8LadkwL0cAOQ9r5D6scY3Bp/ZypDNWvB9uqk1JaRqZc632QdB04t89/1O/w1cDnyilFU='  # Replace with your actual LINE access token
line_user_id = 'U71c990b0b16573a9ffae5367a2717430'  # Replace with your actual LINE user ID

first_dt_text = get_first_dt_text(url)
if first_dt_text:
    send_line_message(line_access_token, line_user_id, first_dt_text)
else:
    print("No dt tag found in the HTML content.")